import type { PanelConfig, MapLayers } from '@/types';
import { SITE_VARIANT } from './variant';

// ============================================
// FULL VARIANT (Geopolitical)
// ============================================
// Panel order matters! First panels appear at top of grid.
// Desired order: live-news, AI Insights, AI Strategic Posture, cii, strategic-risk, then rest
const FULL_PANELS: Record<string, PanelConfig> = {
  map: { name: 'Mapa Global', enabled: true, priority: 1 },
  'live-news': { name: 'Notícias ao Vivo', enabled: true, priority: 1 },
  insights: { name: 'Insights de IA', enabled: true, priority: 1 },
  'strategic-posture': { name: 'Postura Estratégica de IA', enabled: true, priority: 1 },
  cii: { name: 'Instabilidade por País', enabled: true, priority: 1 },
  'strategic-risk': { name: 'Visão Geral de Risco Estratégico', enabled: true, priority: 1 },
  intel: { name: 'Feed de Inteligência', enabled: true, priority: 1 },
  'gdelt-intel': { name: 'Inteligência em Tempo Real', enabled: true, priority: 1 },
  cascade: { name: 'Cascata de Infraestrutura', enabled: true, priority: 1 },
  politics: { name: 'Notícias Mundiais', enabled: true, priority: 1 },
  middleeast: { name: 'Middle East', enabled: true, priority: 1 },
  africa: { name: 'Africa', enabled: true, priority: 1 },
  latam: { name: 'Latin America', enabled: true, priority: 1 },
  asia: { name: 'Asia-Pacific', enabled: true, priority: 1 },
  energy: { name: 'Energia e Recursos', enabled: true, priority: 1 },
  gov: { name: 'Governo', enabled: true, priority: 1 },
  thinktanks: { name: 'Think Tanks', enabled: true, priority: 1 },
  polymarket: { name: 'Previsões', enabled: true, priority: 1 },
  commodities: { name: 'Commodities', enabled: true, priority: 1 },
  markets: { name: 'Mercados', enabled: true, priority: 1 },
  economic: { name: 'Indicadores Econômicos', enabled: true, priority: 1 },
  finance: { name: 'Finanças', enabled: true, priority: 1 },
  tech: { name: 'Tecnologia', enabled: true, priority: 2 },
  crypto: { name: 'Crypto', enabled: true, priority: 2 },
  heatmap: { name: 'Mapa de Calor Setorial', enabled: true, priority: 2 },
  ai: { name: 'AI/ML', enabled: true, priority: 2 },
  layoffs: { name: 'Monitor de Demissões', enabled: true, priority: 2 },
  monitors: { name: 'Meus Monitores', enabled: true, priority: 2 },
  'satellite-fires': { name: 'Incêndios', enabled: true, priority: 2 },
  'macro-signals': { name: 'Radar de Mercado', enabled: true, priority: 2 },
  'etf-flows': { name: 'Rastreador de ETF de BTC', enabled: true, priority: 2 },
  stablecoins: { name: 'Stablecoins', enabled: true, priority: 2 },
  'ucdp-events': { name: 'Eventos de Conflito UCDP', enabled: false, priority: 2 },
  displacement: { name: 'Deslocamento UNHCR', enabled: false, priority: 2 },
  climate: { name: 'Anomalias Climáticas', enabled: false, priority: 2 },
  'population-exposure': { name: 'Exposição Populacional', enabled: false, priority: 2 },
};

const FULL_MAP_LAYERS: MapLayers = {
  conflicts: true,
  bases: true,
  cables: false,
  pipelines: false,
  hotspots: true,
  ais: false,
  nuclear: true,
  irradiators: false,
  sanctions: true,
  weather: true,
  economic: true,
  waterways: true,
  outages: true,
  cyberThreats: false,
  datacenters: false,
  protests: false,
  flights: false,
  military: true,
  natural: true,
  spaceports: false,
  minerals: false,
  fires: false,
  // Data source layers
  ucdpEvents: false,
  displacement: false,
  climate: false,
  // Tech layers (disabled in full variant)
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
};

const FULL_MOBILE_MAP_LAYERS: MapLayers = {
  conflicts: true,
  bases: false,
  cables: false,
  pipelines: false,
  hotspots: true,
  ais: false,
  nuclear: false,
  irradiators: false,
  sanctions: true,
  weather: true,
  economic: false,
  waterways: false,
  outages: true,
  cyberThreats: false,
  datacenters: false,
  protests: false,
  flights: false,
  military: false,
  natural: true,
  spaceports: false,
  minerals: false,
  fires: false,
  // Data source layers
  ucdpEvents: false,
  displacement: false,
  climate: false,
  // Tech layers (disabled in full variant)
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
};

// ============================================
// TECH VARIANT (Tech/AI/Startups)
// ============================================
const TECH_PANELS: Record<string, PanelConfig> = {
  map: { name: 'Mapa Global de Tecnologia', enabled: true, priority: 1 },
  'live-news': { name: 'Manchetes de Tecnologia', enabled: true, priority: 1 },
  insights: { name: 'Insights de IA', enabled: true, priority: 1 },
  ai: { name: 'Notícias de IA/ML', enabled: true, priority: 1 },
  tech: { name: 'Tecnologia', enabled: true, priority: 1 },
  startups: { name: 'Startups e VC', enabled: true, priority: 1 },
  vcblogs: { name: 'Insights e Artigos de VC', enabled: true, priority: 1 },
  regionalStartups: { name: 'Notícias Globais de Startups', enabled: true, priority: 1 },
  unicorns: { name: 'Monitor de Unicórnios', enabled: true, priority: 1 },
  accelerators: { name: 'Aceleradoras e Demo Days', enabled: true, priority: 1 },
  security: { name: 'Cibersegurança', enabled: true, priority: 1 },
  policy: { name: 'Política e Regulação de IA', enabled: true, priority: 1 },
  regulation: { name: 'Painel de Regulação de IA', enabled: true, priority: 1 },
  layoffs: { name: 'Monitor de Demissões', enabled: true, priority: 1 },
  markets: { name: 'Ações de Tecnologia', enabled: true, priority: 2 },
  finance: { name: 'Notícias Financeiras', enabled: true, priority: 2 },
  crypto: { name: 'Crypto', enabled: true, priority: 2 },
  hardware: { name: 'Semicondutores e Hardware', enabled: true, priority: 2 },
  cloud: { name: 'Nuvem e Infraestrutura', enabled: true, priority: 2 },
  dev: { name: 'Comunidade de Desenvolvedores', enabled: true, priority: 2 },
  github: { name: 'GitHub Trending', enabled: true, priority: 1 },
  ipo: { name: 'IPO e SPAC', enabled: true, priority: 2 },
  polymarket: { name: 'Previsões de Tecnologia', enabled: true, priority: 2 },
  funding: { name: 'Captação e VC', enabled: true, priority: 1 },
  producthunt: { name: 'Product Hunt', enabled: true, priority: 1 },
  events: { name: 'Eventos de Tecnologia', enabled: true, priority: 1 },
  'service-status': { name: 'Status de Serviços', enabled: true, priority: 2 },
  economic: { name: 'Indicadores Econômicos', enabled: true, priority: 2 },
  'tech-readiness': { name: 'Índice de Prontidão Tecnológica', enabled: true, priority: 1 },
  'macro-signals': { name: 'Radar de Mercado', enabled: true, priority: 2 },
  'etf-flows': { name: 'Rastreador de ETF de BTC', enabled: true, priority: 2 },
  stablecoins: { name: 'Stablecoins', enabled: true, priority: 2 },
  monitors: { name: 'Meus Monitores', enabled: true, priority: 2 },
};

const TECH_MAP_LAYERS: MapLayers = {
  conflicts: false,
  bases: false,
  cables: true,
  pipelines: false,
  hotspots: false,
  ais: false,
  nuclear: false,
  irradiators: false,
  sanctions: false,
  weather: true,
  economic: true,
  waterways: false,
  outages: true,
  cyberThreats: false,
  datacenters: true,
  protests: false,
  flights: false,
  military: false,
  natural: true,
  spaceports: false,
  minerals: false,
  fires: false,
  // Data source layers
  ucdpEvents: false,
  displacement: false,
  climate: false,
  // Tech layers (enabled in tech variant)
  startupHubs: true,
  cloudRegions: true,
  accelerators: false,
  techHQs: true,
  techEvents: true,
};

const TECH_MOBILE_MAP_LAYERS: MapLayers = {
  conflicts: false,
  bases: false,
  cables: false,
  pipelines: false,
  hotspots: false,
  ais: false,
  nuclear: false,
  irradiators: false,
  sanctions: false,
  weather: false,
  economic: false,
  waterways: false,
  outages: true,
  cyberThreats: false,
  datacenters: true,
  protests: false,
  flights: false,
  military: false,
  natural: true,
  spaceports: false,
  minerals: false,
  fires: false,
  // Data source layers
  ucdpEvents: false,
  displacement: false,
  climate: false,
  // Tech layers (limited on mobile)
  startupHubs: true,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: true,
};

// ============================================
// VARIANT-AWARE EXPORTS
// ============================================
export const DEFAULT_PANELS = SITE_VARIANT === 'tech' ? TECH_PANELS : FULL_PANELS;
export const DEFAULT_MAP_LAYERS = SITE_VARIANT === 'tech' ? TECH_MAP_LAYERS : FULL_MAP_LAYERS;
export const MOBILE_DEFAULT_MAP_LAYERS = SITE_VARIANT === 'tech' ? TECH_MOBILE_MAP_LAYERS : FULL_MOBILE_MAP_LAYERS;

export const MONITOR_COLORS = [
  '#44ff88',
  '#ff8844',
  '#4488ff',
  '#ff44ff',
  '#ffff44',
  '#ff4444',
  '#44ffff',
  '#88ff44',
  '#ff88ff',
  '#88ffff',
];

export const STORAGE_KEYS = {
  panels: 'worldmonitor-panels',
  monitors: 'worldmonitor-monitors',
  mapLayers: 'worldmonitor-layers',
  disabledFeeds: 'worldmonitor-disabled-feeds',
} as const;
